### ISSUE TITLE
What kind of esp32-wrover specific in this project? 

### ISSUE THREAD

**Issue by colesnicov** [ctag-fh-kiel/esp32-eurorack-audio#2]
Good day. I want to ask **what kind of esp32-wrover specific in this project**? There are a lot of them, and I don't know much about them, so I don't want to make a mistake, I'd rather ask. **Which ones are guaranteed to work for me here?** [Here (_mouser_)](https://eu.mouser.com/Search/Refine?Keyword=ESP32-WROVER) I found **esp32-wrover**, **esp32-wrover-e**, **esp32-wrover-i**, **esp32-wrover-ie**, **esp32-wrover-b**, **esp32-wrover-ib**... Thank you for your help.

**Comment by ctag-fh-kiel** [comment]
You need a wrover with 16MB flash and at least 4 MB SPI RAM, it depends if you want external antenna, if so, chose WROVER with IPEX connector.
Component details are here https://github.com/ctag-fh-kiel/esp32-eurorack-audio/blob/rev-d/ESP32-Eurorack-Audio-BOM-RevD.xlsx spreadsheet.
esp32-wrover-ie is the newest one, should work well too. In the bom is esp32-wrover-ib

**Comment by colesnicov** [comment]
Thank you.

**Comment by colesnicov** [comment]
Hi. I'm sorry, but I'm here again. I'm looking at the BOM file you wrote me the link above, and at the same time I have a project open in the kicad from the address https://github.com/ctag-fh-kiel/esp32-eurorack-audio. And I see here that the components that are listed in the BOM file are missing here in the project. Can you please explain to me which project it is, sw, hw, bom? It seems to me you have it scattered over different folders + duplication..  :-/ 

**It should be stated in the BOM: C508, C507, C503, C506, C505 = 4.7uF but in the project C505 = 100nF (not 4.7uF !!) and C503, C506, C507, C508 are missing** in the project. It can't work like this ..

**Comment by colesnicov** [comment]
Or one more time. These are two different projects, but do **they use the same esp32-wrover module?** HMM, I'm confused. Correctly?

**Comment by colesnicov** [comment]
I've got it. I'm sorry :)

**Comment by ctag-fh-kiel** [comment]
No problem ;) The project is pretty well structured. Everything regarding hardware is in the hw folder. All other folders are relevant for SW (firmware + simulator). 
hw/frontplate are gerbers for a frontplate design.
hw/pcb are all KiCad and gerbers for the hardware.
Note that the current design uses QFNs + 0402s which are very advanced for handsoldering.
Let me know if you spot any errors in the bom.xlsx file, I will try to fix and am grateful for help sorting out issues.

**Comment by colesnicov** [comment]
No no, we probably don't understand each other. I want to build for a friend [this CTAG Strämpler](https://github.com/ctag-fh-kiel/ctag-straempler)

I went through your repository and I understood it like this:
https://github.com/ctag-fh-kiel/esp32-eurorack-audio is hardware
https://github.com/ctag-fh-kiel/ctag-straempler is software
https://github.com/ctag-fh-kiel/ctag-tbd is something else (add-on module) ...

It's right?

**Comment by ctag-fh-kiel** [comment]
Ah, got you, sorry, I was at the TBD ;) 
Yes, you are right! Sorry for the confusion.
Forget my previous comment...

**Comment by ctag-fh-kiel** [comment]
BOM is here https://github.com/ctag-fh-kiel/esp32-eurorack-audio/blob/rev-d/ESP32-Eurorack-Audio-BOM-RevD.xlsx

**Comment by colesnicov** [comment]
No problem. Thank you for your help ;)

**Comment by colesnicov** [comment]
Hi. I'm bothering again :) I can't opt for some of the ESP32-wrover module. There is a note in the BOM file that I have to use 'WROVER-B' otherwise non-B has problems booting. Could you please tell me which of the modules I should buy here is the [link to the mouser](https://cz.mouser.com/Espressif/WiFi-Modules-80211/ESP32-WROVER-Series/_/N-1y98oj6Z6l7qaZ1y94wm8)? I did not find a version with 16 MB but there are others. I'm a dick. I don't work much with ESP, so I can't decide.

**Comment by ctag-fh-kiel** [comment]
You can use this one ESP32-WROVER-IE, ESP32-D0WD-V3, 3.3V 64Mbit PSRAM, 16 MB SPI flash, IPEX connector:
https://www.mouser.de/ProductDetail/Espressif-Systems/ESP32-WROVER-IEM213EH2864UH3Q0/?qs=vmHwEFxEFR97Z2otHlKj0Q%3D%3D

**Comment by colesnicov** [comment]
OK. I'll try. Thank you for the recommendation.
